### ISSUE TITLE
What's the point of making `in_array` strict and breaking all my projects?

### ISSUE THREAD

**Issue by OzanKurt** [LaravelCollective/html#374]
```php
    /**
     * Determine if the value is selected.
     *
     * @param  string $value
     * @param  string $selected
     *
     * @return null|string
     */
    protected function getSelectedValue($value, $selected)
    {
        if (is_array($selected)) {
            return in_array($value, $selected) ? 'selected' : null; // Just remove the 3rd parameter...
        } elseif ($selected instanceof Collection) {
            return $selected->contains($value) ? 'selected' : null;
        }

        return ((string) $value == (string) $selected) ? 'selected' : null;
    }
```

**Comment by OzanKurt** [comment]
Laravel automatically converts array values to `string`s, if you do this check strict, none of the multiple selects will work by default.

**Comment by dtbarne** [comment]
We have the same issue. This is a breaking change.

**Comment by OzanKurt** [comment]
Because of this undocumented change, I had troubles with my company. Please be more careful when applying "fixes".

**Comment by OzanKurt** [comment]
Bump!

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/368

**Comment by cham11ng** [comment]
seems https://github.com/LaravelCollective/html/pull/368 gonna take forever to merge 
CI test failed
> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty` 

How you guys are dealing with this issue?

**Comment by decadence** [comment]
Support of this repo is periodical so all we have is waiting.

**Comment by piperone** [comment]
Somebody done messed up. Hope this issue is fixed soon.

**Comment by Machecek** [comment]
@piperone , @decadence , @cham11ng https://github.com/LaravelCollective/html/pull/354?_pjax=%23js-repo-pjax-container#issuecomment-320009845

**Comment by piperone** [comment]
Thanks @Machecek. I ended up not using the Form-facade for my use case. I found it easier to just loop through ```old()```manually.

**Comment by OzanKurt** [comment]
I forked it and started building it according to my needs, for example adding macros for select2 and bootstrap classes.

Ozan Kurt

**Comment by bcalik** [comment]
This issue still exists on the package v5.2.6.
Downgrading to v5.2.5 solved my issue.

**Comment by OlivierCoilland** [comment]
Downgraded to 5.1.9 for 5.1.* branch.

**Comment by tshafer** [comment]
Is this still an issue?

**Comment by bcalik** [comment]
@tshafer probably fixed by this commit: https://github.com/LaravelCollective/html/commit/0c1a869f4c069883592deebf10ccd0dd529155b5

But I did not test it. I'm still using the old version.

**Comment by OzanKurt** [comment]
@tshafer No, it is fine now.

**Comment by servani** [comment]
Still an issue on branch 5.3 (tag 5.3.2). Can we remove the strict mode?
